schema = """
-- MySQL Script generated by MySQL Workbench
-- Wed Jul  9 21:22:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema meu_projeto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema meu_projeto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `meu_projeto` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `meu_projeto` ;

-- -----------------------------------------------------
-- Table `meu_projeto`.`alembic_version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_projeto`.`alembic_version` (
  `version_num` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`version_num`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meu_projeto`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_projeto`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  `author` VARCHAR(128) NOT NULL,
  `isbn` VARCHAR(13) NOT NULL,
  `publisher` VARCHAR(128) NULL DEFAULT NULL,
  `publication_year` INT NULL DEFAULT NULL,
  `edition` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `isbn` (`isbn` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meu_projeto`.`book_copy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_projeto`.`book_copy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `copy_number` INT NOT NULL,
  `is_available` TINYINT(1) NULL DEFAULT NULL,
  `condition` VARCHAR(32) NULL DEFAULT NULL,
  `location` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `book_id` (`book_id` ASC) VISIBLE,
  CONSTRAINT `book_copy_ibfk_1`
    FOREIGN KEY (`book_id`)
    REFERENCES `meu_projeto`.`book` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meu_projeto`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_projeto`.`cargo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(64) NOT NULL,
  `descricao` VARCHAR(256) NULL DEFAULT NULL,
  `salario_base` FLOAT NOT NULL,
  `nivel_hierarquico` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome` (`nome` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meu_projeto`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_projeto`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(128) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `email` VARCHAR(64) NULL DEFAULT NULL,
  `telefone` VARCHAR(16) NULL DEFAULT NULL,
  `endereco` VARCHAR(256) NULL DEFAULT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meu_projeto`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_projeto`.`cliente` (
  `id` INT NOT NULL,
  `data_cadastro` DATE NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `cliente_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `meu_projeto`.`pessoa` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meu_projeto`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_projeto`.`empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(14) NOT NULL,
  `razao_social` VARCHAR(128) NOT NULL,
  `nome_fantasia` VARCHAR(128) NULL DEFAULT NULL,
  `numero_contato` VARCHAR(16) NULL DEFAULT NULL,
  `email_contato` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meu_projeto`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_projeto`.`emprestimo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `livro_copia_id` INT NOT NULL,
  `data_retirada` DATETIME NOT NULL,
  `data_devolucao_prevista` DATETIME NOT NULL,
  `data_devolucao_real` DATETIME NULL DEFAULT NULL,
  `valor_multa` FLOAT NULL DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cliente_id` (`cliente_id` ASC) VISIBLE,
  INDEX `livro_copia_id` (`livro_copia_id` ASC) VISIBLE,
  CONSTRAINT `emprestimo_ibfk_1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `meu_projeto`.`cliente` (`id`),
  CONSTRAINT `emprestimo_ibfk_2`
    FOREIGN KEY (`livro_copia_id`)
    REFERENCES `meu_projeto`.`book_copy` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meu_projeto`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_projeto`.`funcionario` (
  `id` INT NOT NULL,
  `cargo_id` INT NOT NULL,
  `data_contratacao` DATE NOT NULL,
  `salario` FLOAT NOT NULL,
  `ativo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `cargo_id` (`cargo_id` ASC) VISIBLE,
  CONSTRAINT `funcionario_ibfk_1`
    FOREIGN KEY (`cargo_id`)
    REFERENCES `meu_projeto`.`cargo` (`id`),
  CONSTRAINT `funcionario_ibfk_2`
    FOREIGN KEY (`id`)
    REFERENCES `meu_projeto`.`pessoa` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

"""